--Create empty Housing DB
DROP TABLE IF EXISTS developments CASCADE;
CREATE TABLE developments (
	job_number text,
	job_type text,
	job_description text,
	occ_init text,
	occ_prop text,
	occ_category text,
	stories_init text,
	stories_prop text,
	zoningsft_init text,
	zoningsft_prop text,
	units_init text,
	units_prop text,
	units_net text,
	units_complete text,
	units_incomplete text,
	co_earliest_effectivedate text,
	co_latest_effectivedate text,
	co_latest_certtype text,
	co_latest_units text,
	status text,
	status_date text,
	status_a text,
	status_d text,
	status_p text,
	status_q text,
	status_r text,
	status_x text,
	address_house text,
	address_street text,
	address text,
	bin text,
	bbl text,
	boro text,
	geo_address_house text,
	geo_address_street text,
	geo_address text,
	geo_bin text,
	geo_bbl text,
	geo_boro text,
	geo_cd text,
	geo_ntacode2010 text,
	geo_censusblock2010 text,
	geo_csd text,
	geo_council text,
	x_dcpedited text,
 	x_mixeduse text,
	x_inactive text,
	x_outlier text,
	x_withdrawal text,
	x_geomsource text,
	x_reason text,
	latitude text,
	longitude text	
);
-- add a geometry column
SELECT AddGeometryColumn ('public','developments','geom',4326,'Geometry',2);