INSERT INTO developments (
	job_number,
	job_type,
	job_description,
	occ_init,
	occ_prop,
	stories_init,
	stories_prop,
	zoningsft_init,
	zoningsft_prop,
	units_init,
	units_prop,
	status,
	status_date,
	status_a,
	status_d,
	status_p,
	status_r,
	status_x,
	address_house,
	address_street,
	bin,
	bbl,
	boro,
	x_withdrawal,
	latitude,
	longitude
	)
SELECT 
	jobnumber,
	jobtype,
	jobdescription,
	existingoccupancy,
	proposedoccupancy,
	existingnumstories,
	proposednumstories,
	existingzoningsqft,
	proposedzoningsqft,
	existingdwellingunits,
	proposeddwellingunits,
	jobstatusdesc,
	latestactiondate,
	prefilingdate,
	fullypaid,
	approved,
	fullypermitted,
	signoffdate,
	housenumber,
	streetname,
	bin,
	lpad(block, 5, '0')||lpad(RIGHT(lot,4), 4, '0'),
	borough,
	specialactionstatus,
	latitude,
	longitude	
FROM dob_jobapplications
WHERE jobdocnumber = '01' 
	AND (jobtype = 'A1' OR jobtype = 'DM' OR jobtype = 'NB');